# Using Monte Carlo Simulation to Determine the Optimal Portfolio of Stocks

If you have tried investing in the stock market, then you are most likely faced with multiple investment decisions such as "which stock to choose", "which industry to focus on" and "how much should you allocate to each stock".
Fortunately, Harry Markowitz provided an answer to the last question which is also considered as one of the most difficult problems in investing: portfolio security selection. 

His Moden Portfolio Theory (MPT) won him a Nobel Prize and introduced the ideas of portfolio investing and how securities' risks and correlations impact the portfolio as a whole.
So you might think that there are many ways to answer the question "How much should I invest in a stock", but optimization theories and Markowitz's work would tell you that there is only one correct answer.
There are two ways to solve this problem:

1.  **Analytically** -  which uses linear algebra and matrix operations to arrive at the optimal portfolio.

2.  **Computationally** -  with the use of computers to crunch possible permutations of the portfolio. The optimal portfolio would be the one with the highest return per risk portfolio.

Note that in portfolio optimization, what we optimize is that of the weights or the allocation, given a list of possible investments. 

To get our stock data, we will employ the investpy package.

## PRELIMINARIES

In [1]:
# For Monte Carlo
import random
from time import sleep

# Historical Data
import investpy
import numpy as np
import pandas as pd
import yfinance as yf
from tqdm.notebook import tqdm

# import hvplot.pandas  # noqa


# Visualization
# import holoviews as hv

## STEP 1: GET HISTORICAL DATA FOR THE STOCKS OF YOUR CHOICE

Here we have a list of stocks coming from Revolut's stock list. There should be around 800 stocks in this list.
FIrst of all, import the full list.

In [2]:
stocks_list = pd.read_csv("Stock_list.csv", sep=";")

## STEP 2: CALCULATE THE RETURNS FOR THESE STOCKS

To calculate the return, specify the time period in question. This is critical as the choice of the time period may coincide with periods of high growth or periods of depressed growth for the equity market.
We get the stock data, to track the volatility of the market. Ideally, we want a time period that covers the full business cycle, from trough, recession, expansion, and peak.

To begin, specify the stock and past trading dates you are looking at. The past trading dates will provide us the riskiness of the stocks through the standard deviation of their returns.

For now, let us assume that the correct time period that will represent the expected return for the coming year is given by the following:

In [3]:
begin_date = "01/02/2022"
end_date = "23/03/2022"

In [4]:
def generate_stock_returns(stocks_list, begin_date, end_date):

    prices = pd.DataFrame()

    for stock in tqdm(stocks_list):
        try:

            df_ = yf.download(  # or pdr.get_data_yahoo(...
                # tickers list or string as well
                tickers=stock,
                # use "period" instead of start/end
                # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
                # (optional, default is '1mo')
                period="1y",
                # fetch data by interval (including intraday if period < 60 days)
                # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
                # (optional, default is '1d')
                interval="1d",
                # group by ticker (to access via data['SPY'])
                # (optional, default is 'column')
                group_by="column",
                # adjust all OHLC automatically
                # (optional, default is False)
                auto_adjust=False,
                # download pre/post regular market hours data
                # (optional, default is False)
                prepost=False,
                # use threads for mass downloading? (True/False/Integer)
                # (optional, default is True)
                threads=True,
                # proxy URL scheme use use when downloading?
                # (optional, default is None)
                proxy=None,
            ).Close

            # sleep(2)
            # df_ = investpy.get_stock_historical_data(stock=stock,
            #                                        country='united states',
            #                                        from_date=begin_date,
            #                                        to_date=end_date).Close

            df_.rename(stock, inplace=True)
            df_.columns = [stock]
            prices = pd.concat([prices, df_], axis=1)
            prices.index.name = "Date"

        except Exception as e:
            try:
                if (
                    e.args[0]
                    == "ERR#0018: stock "
                    + str.lower(stock)
                    + " not found, check if it is correct."
                ):
                    search_result = investpy.search_quotes(
                        text=stock,
                        countries=["united states"],
                        products=["stocks"],
                        n_results=1,
                    )
                    df_ = search_result.retrieve_historical_data(
                        from_date=begin_date, to_date=end_date
                    ).Close
                    df_.rename(stock, inplace=True)
                    df_.columns = [stock]
                    prices = pd.concat([prices, df_], axis=1)
                    prices.index.name = "Date"
                else:
                    with open("missing_stocks.csv", "a", newline="") as fd:
                        fd.write(stock)
                        fd.write(";\n")

            except Exception as r:
                continue
            continue
    return prices

In [ ]:
prices = generate_stock_returns(stocks_list.Ticker.values, begin_date, end_date)

In [6]:
stocks = prices.columns.values
prices

,NVDA,AMD,PACB,DARD,CORS,CRIS,METT,SATI,ELAN,GNTX,...,HANES,ICICI,QRTEA,STORE,BLOCK,RAPID,MAXAR,GOOGL,CAZOO,IDEXX
Date,,,,,,,,,,,,,,,,,,,,,
2021-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-24,126.430000,76.480003,29.629999,NaN,NaN,10.31,NaN,NaN,28.290001,34.240002,...,NaN,NaN,11.46,NaN,NaN,NaN,NaN,2032.530029,NaN,NaN
2021-03-25,125.352501,76.220001,30.540001,NaN,NaN,11.82,NaN,NaN,28.059999,34.599998,...,NaN,NaN,11.75,NaN,NaN,NaN,NaN,2032.459961,NaN,NaN
2021-03-26,128.392502,77.410004,30.730000,NaN,NaN,11.41,NaN,NaN,27.850000,35.700001,...,NaN,NaN,11.97,NaN,NaN,NaN,NaN,2024.729980,NaN,NaN
2021-03-29,129.482498,77.139999,28.629999,NaN,NaN,11.26,NaN,NaN,28.790001,35.369999,...,NaN,NaN,11.60,NaN,NaN,NaN,NaN,2045.790039,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-17,247.660004,111.690002,10.930000,NaN,9.66,2.82,NaN,NaN,26.610001,29.059999,...,NaN,NaN,5.14,NaN,NaN,NaN,NaN,2676.780029,NaN,NaN
2022-03-18,264.529999,113.459999,10.720000,NaN,9.66,2.78,NaN,NaN,27.420000,29.590000,...,NaN,NaN,5.17,NaN,NaN,NaN,NaN,2722.510010,NaN,NaN
2022-03-21,267.339996,115.919998,9.940000,NaN,9.66,2.62,NaN,NaN,27.200001,29.049999,...,NaN,NaN,5.09,NaN,NaN,NaN,NaN,2722.030029,NaN,NaN
2022-03-22,265.239990,114.779999,10.180000,NaN,9.69,2.63,NaN,NaN,27.410000,29.389999,...,NaN,NaN,5.20,NaN,NaN,NaN,NaN,2797.360107,NaN,NaN
2022-03-23,256.339996,113.919998,9.880000,NaN,NaN,2.46,NaN,NaN,27.219999,28.480000,...,NaN,NaN,4.99,NaN,NaN,NaN,NaN,2765.510010,NaN,NaN

Now we have downloaded all the opening and closing price for every stock for every day in the date range chosed before.

### Returns Calculation

To get the return, we simply use the following code:

In [7]:
returns = prices.pct_change()
returns.head()

,NVDA,AMD,PACB,DARD,CORS,CRIS,METT,SATI,ELAN,GNTX,...,HANES,ICICI,QRTEA,STORE,BLOCK,RAPID,MAXAR,GOOGL,CAZOO,IDEXX
Date,,,,,,,,,,,,,,,,,,,,,
2021-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-25,-0.008522,-0.003400,0.030712,NaN,NaN,0.146460,NaN,NaN,-0.008130,0.010514,...,NaN,NaN,0.025305,NaN,NaN,NaN,NaN,-0.000034,NaN,NaN
2021-03-26,0.024252,0.015613,0.006221,NaN,NaN,-0.034687,NaN,NaN,-0.007484,0.031792,...,NaN,NaN,0.018723,NaN,NaN,NaN,NaN,-0.003803,NaN,NaN
2021-03-29,0.008490,-0.003488,-0.068337,NaN,NaN,-0.013146,NaN,NaN,0.033752,-0.009244,...,NaN,NaN,-0.030911,NaN,NaN,NaN,NaN,0.010401,NaN,NaN

With this formula we got all the daily percentaul changes of stocks value from opening to closing.
Now, let's say we want the list of stocks with the highest percentage of gain between all of them.
We have to calculate the mean percentage of change and sort stocks by mean value. Then get the top 20 performers of between them.

In [8]:
returns.mean().sort_values(ascending=False)[:30].index.values

array(['QUAN', 'AMC ', 'ARCH', 'AA ', 'BKKT', 'AR ', 'RRC ', 'SM ',
       'DVN ', 'MUR ', 'CLR ', 'MTDR', 'MRO ', 'PTEN', 'OXY ', 'BNTX',
       'PDCE', 'SLVM', 'OVV ', 'APA ', 'CF ', 'RES ', 'MOS ', 'TRGP',
       'ENLC', 'CLF ', 'TECK', 'ASAN', 'NUE ', 'CVE '], dtype=object)

### Covariance Matrix

In [9]:
cov = returns.cov()
cov.head()

,NVDA,AMD,PACB,DARD,CORS,CRIS,METT,SATI,ELAN,GNTX,...,HANES,ICICI,QRTEA,STORE,BLOCK,RAPID,MAXAR,GOOGL,CAZOO,IDEXX
NVDA,0.000955,0.000708,0.000768,NaN,0.000007,0.000197,NaN,NaN,0.000214,0.000165,...,NaN,NaN,0.000120,NaN,NaN,NaN,NaN,0.000302,NaN,NaN
AMD,0.000708,0.000938,0.000681,NaN,0.000011,0.000323,NaN,NaN,0.000175,0.000153,...,NaN,NaN,0.000178,NaN,NaN,NaN,NaN,0.000258,NaN,NaN
PACB,0.000768,0.000681,0.002248,NaN,-0.000023,0.000800,NaN,NaN,0.000252,0.000162,...,NaN,NaN,0.000344,NaN,NaN,NaN,NaN,0.000291,NaN,NaN
DARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CORS,0.000007,0.000011,-0.000023,NaN,0.000033,-0.000030,NaN,NaN,0.000003,-0.000003,...,NaN,NaN,-0.000012,NaN,NaN,NaN,NaN,0.000003,NaN,NaN

Now we do have a couple of options.
In the list of best performers we may want:
    a) to analyse stocks and choose between them a sub-list of 5/6 stocks to invest in (like...looking for the market position, sector, performance and so on);
    b) or we may let decide a first run of portfolio optimization which of them worth the highest investment.
    
Let's say we choose to use our head and we figured out a list of 5 stocks worth investing in.
Now go ahead.

In [74]:
stocks_list = ["ARCH", "TRGP", "SLVM", "BNTX", "AA "]

stocks_list = list(dict.fromkeys(stocks_list))
print(stocks_list)

SyntaxError: unmatched ']' (3264410552.py, line 1)

Download the data again, just for our 5 stocks, and calculate pct_changes again.

In [75]:
prices = generate_stock_returns(stocks_list, begin_date, end_date)
stocks = prices.columns.values
returns = prices.pct_change()
cov = returns.cov()
returns.head()

  0%|          | 0/6 [00:00<?, ?it/s]

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                         ARCH      TRGP  SLVM      BNTX      QUAN       AA
Date
2021-03-24 00:00:00       NaN       NaN   NaN       NaN       NaN       NaN
2021-03-25 00:00:00 -0.014717  0.019853   NaN  0.011483  0.310526  0.031293
2021-03-26 00:00:00  0.078987  0.018838   NaN  0.006623 -0.196787  0.105192
2021-03-29 00:00:00 -0.016424 -0.024037   NaN  0.001566  0.000000 -0.022575
2021-03-30 00:00:00 -0.041985  0.003158   NaN  0.088938  0.126250  0.029026

## STEP 3: INITIALIZE THE WEIGHTS AND FUNCTION FOR THE CALCULATION OF METRICS

As we are trying to optimize the portfolio by altering the weight allocation, let's initialize our weights and calculate the initial metrics using our customized function below.

It is important that the weights chosen come from a uniform distribution from 0 to 1. Luckily, random.random of numpy draws from a continuous, uniform distribution.

In [76]:
weights = np.random.random(len(stocks))
weights /= np.sum(weights)
weights

array([0.14837711, 0.19131229, 0.18084933, 0.23642867, 0.19618955,
       0.04684306])

Note that we normalize our weights to equal to 1 or 100% allocation.

### PORTFOLIO RETURNS

Because what we have are daily returns of stocks that we have calculated, we then proceed to annualize these by multiplying the average daily returns with the number of trading days in a year which is 252.

In [77]:
rp = (returns.mean() * 252) @ weights
rp

1.5865522491229869

### PORTFOLIO VARIANCE

Since we have the daily volatility as well, we proceed to annualize these by multiplying them with 252. The formula for the Covariance is given as:

In [78]:
# Portfolio Variance
port_var = weights @ (cov * 252) @ weights
port_var

0.2576628647081302

### SHARPE RATIO

In [79]:
# Sharpe Ratio
rf = 0.02  # risk-free rate
sharpe = (rp - rf) / np.sqrt(port_var)
sharpe

3.08616377287139

## FUNCTION FOR USE

In [80]:
def portfolio_metrics(weights, index="Trial"):

    """
    This function generates the relative performance metrics that will be reported and will be used
    to find the optimal weights.

    Parameters:
    weights: initialized weights or optimal weights for performance reporting

    """

    rp = (returns.mean() * 252) @ weights
    port_var = weights @ (cov * 252) @ weights
    sharpe = (rp - rf) / np.sqrt(port_var)
    df = pd.DataFrame(
        {
            "Expected Return": rp,
            "Portfolio Variance": port_var,
            "Portfolio Std": np.sqrt(port_var),
            "Sharpe Ratio": sharpe,
        },
        index=[index],
    )
    return df


portfolio_metrics(weights)

       Expected Return  Portfolio Variance  Portfolio Std  Sharpe Ratio
Trial         1.586552            0.257663       0.507605      3.086164

## STEP 4:  MONTE CARLO SIMULATION

In [81]:
# np.random.seed(42)
portfolios = pd.DataFrame(
    columns=[
        *stocks,
        "Expected Return",
        "Portfolio Variance",
        "Portfolio Std",
        "Sharpe Ratio",
    ]
)

for i in tqdm(range(10000)):
    weights = np.random.random(len(stocks))
    weights /= np.sum(weights)
    portfolios.loc[i, stocks] = weights
    metrics = portfolio_metrics(weights, i)
    portfolios.loc[
        i, ["Expected Return", "Portfolio Variance", "Portfolio Std", "Sharpe Ratio"]
    ] = metrics.loc[
        i, ["Expected Return", "Portfolio Variance", "Portfolio Std", "Sharpe Ratio"]
    ]

portfolios

  0%|          | 0/10000 [00:00<?, ?it/s]

,ARCH,TRGP,SLVM,BNTX,QUAN,AA,Expected Return,Portfolio Variance,Portfolio Std,Sharpe Ratio
0,0.216791,0.032617,0.198757,0.176528,0.068732,0.306574,1.376695,0.127936,0.357682,3.793021
1,0.000701,0.045902,0.186194,0.357542,0.32847,0.081191,1.909897,0.621234,0.788184,2.397787
2,0.264175,0.186004,0.156774,0.078331,0.23245,0.082265,1.763352,0.299674,0.547425,3.184643
3,0.062233,0.324847,0.303497,0.18545,0.090459,0.033513,1.22684,0.135283,0.367809,3.281162
4,0.099467,0.214033,0.125573,0.300453,0.177038,0.083436,1.523063,0.248259,0.498256,3.01665
...,...,...,...,...,...,...,...,...,...,...
9995,0.063917,0.121659,0.170274,0.311167,0.304787,0.028196,1.848487,0.527538,0.726318,2.517475
9996,0.107194,0.190784,0.21554,0.204504,0.221993,0.059985,1.643563,0.300928,0.548569,2.959632
9997,0.099835,0.174566,0.175804,0.198423,0.124116,0.227257,1.434137,0.160735,0.400918,3.527253
9998,0.276358,0.184964,0.192914,0.222375,0.02241,0.100979,1.180904,0.101453,0.318516,3.644727
9999,0.496286,0.005478,0.152324,0.157821,0.137619,0.050471,1.608667,0.172094,0.414842,3.829566

In [82]:
optimal_portfolio = portfolios[
    portfolios["Sharpe Ratio"] == portfolios["Sharpe Ratio"].max()
].T

In [83]:
amount_to_invest = 1500  # €s to invest
print(amount_to_invest)
optimal_portfolio.rename(
    columns={optimal_portfolio.columns.values[0]: "Weights"}, inplace=True
)
optimal_portfolio["Valore investito"] = (
    optimal_portfolio.Weights * amount_to_invest
).astype(int)
optimal_portfolio.Weights[:-4] = optimal_portfolio.Weights[:-4].map(
    lambda x: "{:.2%}".format(x)
)
optimal_portfolio

1500

/tmp/ipykernel_8627/1086534591.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  optimal_portfolio.Weights[:-4] = optimal_portfolio.Weights[:-4].map(lambda x: '{:.2%}'.format(x))

                     Weights  Valore investito
ARCH                  37.58%               563
TRGP                  13.06%               195
SLVM                  18.48%               277
BNTX                   9.28%               139
QUAN                   7.53%               112
AA                    14.07%               211
Expected Return      1.40075              2101
Portfolio Variance  0.114049               171
Portfolio Std       0.337712               506
Sharpe Ratio        4.088543              6132

In [84]:
optimal_portfolio[:-4].sort_values(by="Valore investito", ascending=False)

     Weights  Valore investito
ARCH  37.58%               563
SLVM  18.48%               277
AA    14.07%               211
TRGP  13.06%               195
BNTX   9.28%               139
QUAN   7.53%               112

In [85]:
optimal_portfolio[:-4].sort_values(by="Valore investito", ascending=False)[:14].index

Index(['ARCH', 'SLVM', 'AA ', 'TRGP', 'BNTX', 'QUAN'], dtype='object')

In [89]:
stocks

array(['AR ', 'NUE ', 'AA ', 'ENLC', 'CVE ', 'QUAN', 'RRC ', 'OXY '],
      dtype=object)